/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.14
 * Generated at: 2017-08-08 08:14:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>众筹系统</title>\r\n");
      out.write("<!-- 插件 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"static/loading/loading.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"static/pagination/pagination.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"static/bootstrap/bootstrap.min.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"static/jquery/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"static/bootstrap/bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"static/validate/jquery.validate.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"static/validate/messages_zh.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"static/pagination/pagination.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"static/loading/loading.js\"></script>\r\n");
      out.write("<!-- 代码 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"static/dist/list.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"static/dist/list.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");

	int totalNum = (int) request.getAttribute("totalNum");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t// 总记录\r\n");
      out.write("\t\tvar totalNum = $\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\ttotalNum\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t;\r\n");
      out.write("\t\t$(\"#pagination\").pagination(totalNum, {\r\n");
      out.write("\t\t\tcallback : pageCallback,\r\n");
      out.write("\t\t\tprev_text : '<<<',\r\n");
      out.write("\t\t\tnext_text : '>>>',\r\n");
      out.write("\t\t\tellipse_text : '...',\r\n");
      out.write("\t\t\tcurrent_page : 0, // 当前选中的页面\r\n");
      out.write("\t\t\titems_per_page : 5, // 每页显示的条目数\r\n");
      out.write("\t\t\tnum_display_entries : 4, // 连续分页主体部分显示的分页条目数\r\n");
      out.write("\t\t\tnum_edge_entries : 1\r\n");
      out.write("\t\t// 两侧显示的首尾分页的条目数\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tfunction pageCallback(index, jq) {\r\n");
      out.write("\t\t\t// 清空表格\r\n");
      out.write("\t\t\t$(\"#table\").empty();\r\n");
      out.write("\t\t\tget(index);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction get(index) {\r\n");
      out.write("\t\t\t$\r\n");
      out.write("\t\t\t\t\t.ajax({\r\n");
      out.write("\t\t\t\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\t\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\t\t\t\turl : 'getFunds',\r\n");
      out.write("\t\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t\t\"pageIndex\" : index\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\tbeforeSend : function() {\r\n");
      out.write("\t\t\t\t\t\t\t// 显示loading\r\n");
      out.write("\t\t\t\t\t\t\tloading();\r\n");
      out.write("\t\t\t\t\t\t}, // beforeSend\r\n");
      out.write("\t\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\t// 后台返回结果为空\r\n");
      out.write("\t\t\t\t\t\t\tif ($.isEmptyObject(data)) {\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#table\").append(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t'<p class=\"text-danger\">暂无众筹</p>');\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t// 后台返回结果非空\r\n");
      out.write("\t\t\t\t\t\t\telse {\r\n");
      out.write("\t\t\t\t\t\t\t\tvar tab = \"\";\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t// thead\r\n");
      out.write("\t\t\t\t\t\t\t\ttab += '<thead><tr>';\r\n");
      out.write("\t\t\t\t\t\t\t\ttab += '<th>编号</th>';\r\n");
      out.write("\t\t\t\t\t\t\t\ttab += '<th>众筹地址</th>';\r\n");
      out.write("\t\t\t\t\t\t\t\ttab += '<th>已筹人数</th>';\r\n");
      out.write("\t\t\t\t\t\t\t\ttab += '<th>已筹金币</th>';\r\n");
      out.write("\t\t\t\t\t\t\t\ttab += '<th>操作</th>';\r\n");
      out.write("\t\t\t\t\t\t\t\ttab += '<tr></thead>';\r\n");
      out.write("\t\t\t\t\t\t\t\t// tbody\r\n");
      out.write("\t\t\t\t\t\t\t\ttab += '<tbody>';\r\n");
      out.write("\t\t\t\t\t\t\t\t$\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t.each(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tfunction(i, fund) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttab += '<tr>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttab += '<td>' + i + '</td>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttab += '<td>'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ fund['owner']\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ '</td>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttab += '<td>'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ fund['number']\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ '</td>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttab += '<td>'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ fund['coin']\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ '</td>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttab += '<td>'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ '<button type=\"button\" class=\"btn btn-primary btn-sm\"'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ 'data-toggle=\"modal\" data-target=\"#myModal\"'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ 'onclick=\"select('\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"'\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ fund['owner']\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"'\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ ')\">我要捐赠</button>'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ '</td>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttab += '</tr>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\ttab += '</tbody>';\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#table\").append(tab);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}, // success\r\n");
      out.write("\t\t\t\t\t\tcomplete : function() {\r\n");
      out.write("\t\t\t\t\t\t\t// 隐藏loading\r\n");
      out.write("\t\t\t\t\t\t\tremoveLoading('loading');\r\n");
      out.write("\t\t\t\t\t\t} // complete\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"jumbotron\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<h2 class=\"text-muted\">众筹列表</h2>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 表格 -->\r\n");
      out.write("\t\t\t<table id=\"table\" class=\"table\"></table>\r\n");
      out.write("\t\t\t<!-- 加载 -->\r\n");
      out.write("\t\t\t<div id=\"loading\"></div>\r\n");
      out.write("\t\t\t<!-- 分页 -->\r\n");
      out.write("\t\t\t<div id=\"pagination\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn btn-success btn-lg\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"modal\" data-target=\"#myModal2\">我要众筹</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 模态框1（Modal） -->\r\n");
      out.write("\t<div class=\"modal fade\" id=\"myModal\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("\t\taria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\taria-hidden=\"true\">×</button>\r\n");
      out.write("\t\t\t\t\t<h4 class=\"modal-title\" id=\"myModalLabel\">发送金币</h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t<form class=\"form-horizontal\" role=\"form\" id=\"myForm\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"owner\" class=\"col-sm-2 control-label\">地址</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"owner\" name=\"owner\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"0x...\" readOnly />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"coin\" class=\"col-sm-2 control-label\">金币</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"coin\" name=\"coin\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"password\" class=\"col-sm-2 control-label\">密码</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" id=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"password\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"file\" class=\"col-sm-2 control-label\">钱包</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"file\" id=\"file\" name=\"file\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">关闭</button>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" id=\"confirm\">确认</button>\r\n");
      out.write("\t\t\t\t\t<span id=\"tip\"> </span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /.modal-content -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.modal-dialog -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- /.modal -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- 模态框2（Modal） -->\r\n");
      out.write("\t<div class=\"modal fade\" id=\"myModal2\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("\t\taria-labelledby=\"myModalLabel2\" aria-hidden=\"true\">\r\n");
      out.write("\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\taria-hidden=\"true\">×</button>\r\n");
      out.write("\t\t\t\t\t<h4 class=\"modal-title\" id=\"myModalLabel2\">发起众筹</h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t<form class=\"form-horizontal\" role=\"form\" id=\"myForm2\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"owner2\" class=\"col-sm-2 control-label\">地址</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"owner2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"owner2\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">关闭</button>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" id=\"confirm2\">确认</button>\r\n");
      out.write("\t\t\t\t\t<span id=\"tip2\"> </span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /.modal-content -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.modal-dialog -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- /.modal -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
